name: app_forge
description: Build mobile apps from Figma designs with AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Backend & Database
  supabase_flutter: ^2.3.2
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  
  # Image & File
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # Permissions
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts (if needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700